language: python
dist: trusty
python:
  - "2.7"
notifications: 
  email: false
install: 
  - "pip install -r requirements.txt"
  - "pip install nose"
script: "python -m nose pympc --exclude=test_MPCController --exclude=test__MPCHybridController --exclude=test_linear_program --exclude=test_quadratic_program"
